Add diagnostics

diff --git a/ci-info b/ci-info
--- a/ci-info
+++ b/ci-info
@@ -1,65 +1,76 @@
-#!/bin/bash
-# bash because this script uses arrays
+#!/bin/sh
 
-# Outputs information about a CI job, when run under Azure Pipelines,
-# CircleCI, GitHub Actions, or Travis CI.
+# Determines the start and end commits for a CI job.
+# Works under Azure Pipelines, CircleCI, GitHub Actions, and Travis CI.
 
 # Typical use:
 #
-#   if [ -d /tmp/$USER/plume-scripts ] ; then
-#     git -C /tmp/$USER/plume-scripts pull -q > /dev/null 2>&1
+#   if [ -d /tmp/plume-scripts ] ; then
+#     git -C /tmp/plume-scripts pull -q > /dev/null 2>&1
 #   else
-#     mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth=1 -q https://github.com/plume-lib/plume-scripts.git
+#     mkdir -p /tmp && git -C /tmp clone --depth=1 -q https://github.com/plume-lib/plume-scripts.git
 #   fi
-#   eval $(/tmp/$USER/plume-scripts/ci-info DEFAULT-ORGANIZATION)
+#   eval "$(/tmp/plume-scripts/git-changes DEFAULT-ORGANIZATION)"
 #
-# Here are the variables that it sets:
-# CI_IS_PULL_REQUEST: Either "true" or "false" (without the quotes).
-# CI_ORGANIZATION: The GitHub organization.  In a PR, refers to the source or head.
-#   Optional argument DEFAULT-ORGANIZATION is used if no organization can be determined.
-# CI_BRANCH_NAME: The name of the source/head branch (in a PR) or of the branch being tested.
+# Alternatively, to use a specific version of this script rather than the latest:
+#
+#   if [ ! -d /tmp/plume-scripts ] ; then
+#     mkdir -p /tmp/$USER
+#     git -C /tmp/$USER clone --revision=e768754ffafad4a9f1e26c5305591d4061d890b4 --depth=1 -q https://github.com/plume-lib/plume-scripts.git
+#   fi
+#   eval "$(/tmp/plume-scripts/git-changes DEFAULT-ORGANIZATION)"
+
+# Either snippet of code sets these variables:
 # CI_COMMIT_RANGE: An argument to `git diff` with the range of commits IDs.
 #    (Don't use it with `git log`, which interprets its argument differently.)
-# CI_COMMIT_RANGE_START: The start element of CI_COMMIT_RANGE, a commit ID.
-# CI_COMMIT_RANGE_END: The end element of CI_COMMIT_RANGE, a commit ID.
+# CI_COMMIT_RANGE_START: The start element of CI_COMMIT_RANGE, a commit ID/SHA.
+# CI_COMMIT_RANGE_END: The end element of CI_COMMIT_RANGE, a commit ID/SHA.
 #
-# For example use, see comments in file `ci-lint-diff` in this directory.
-#
-# Requires the `jq` program to be installed, when used in Azure Pipelines jobs.
+# If called not under CI, or under CI but not in the main or toplevel
+# clone, then gets information from the local repository.
+
+# Requires the `jq` program and either `curl` or `wget`.
 #
 # If environment variable GITHUB_PAT or GH_TOKEN is set when this script is
 # called, it is used as GitHub Personal Access Token when making GitHub API
 # calls.  This can avoid "403 rate limit exceeded" failures.
 
-# PROBLEM: The directory from which ci-info is running must override environment
+# PROBLEM: The directory from which git-changes is running must override environment
 # variables, because a CI job may itself call "git clone" and then later call
-# ci-info from that clone.  Idea: check the directory name.
+# git-changes from that clone.  Idea: check the directory name.
 
 # SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
 SCRIPT_NAME="$(basename -- "$0")"
 
 DEBUG=""
-if [ "$1" = "--verbose" ]; then
-  VERBOSE="--verbose"
+DEFAULT_ORGANIZATION=""
+while [ "$#" -gt 0 ]; do
+  case $1 in
+    --verbose)
+      VERBOSE="--verbose"
+      ;;
+    --debug)
+      DEBUG="--debug"
+      VERBOSE="--verbose"
+      ;;
+    *)
+      if [ -n "${DEFAULT_ORGANIZATION}" ]; then
+        usage="Usage: ${SCRIPT_NAME} [--verbose] [--debug] [DEFAULT-ORGANIZATION]"
+        echo "echo \"$usage\";"
+        echo "$usage" >&2
+        echo "exit 2"
+        exit 2
+      else
+        DEFAULT_ORGANIZATION="$1"
+      fi
+      ;;
+  esac
   shift
-fi
-
-if [ "$1" = "--debug" ]; then
-  DEBUG="--debug"
-  VERBOSE="--verbose"
-  shift
-fi
-if [ "$#" -gt 1 ]; then
-  usage="Usage: ${SCRIPT_NAME} [--verbose] [--debug] [DEFAULT-ORGANIZATION]"
-  echo "echo \"$usage\";"
-  echo "$usage" >&2
-  echo "exit 2"
-  exit 2
-fi
+done
 
 if [ "$DEBUG" = "--debug" ]; then
   # `env` only prints EXPORTED variables, so `set` is usually more useful.
-  echo "echo ci-info is running in $(pwd)"
+  echo "echo ${SCRIPT_NAME} is running in $(pwd)"
   echo
   echo 'echo ---------------- start of env'
   env -0 | sort -z | tr '\0' '\n' | sed -e 's/^/echo /'
@@ -87,6 +98,32 @@ if [ "$DEBUG" = "--debug" ]; then
   echo
 fi
 
+### Variables
+
+# "GITHUB_PAT" is a GitHub Personal Access Token.
+# TODO: Should this be "Authorization: Bearer <YOUR-TOKEN>" instead?  See https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request
+if [ -n "$GITHUB_PAT" ]; then
+  auth_header_option="--header=Authorization: token ${GITHUB_PAT}"
+elif [ -n "$GH_TOKEN" ]; then
+  auth_header_option="--header=Authorization: token ${GH_TOKEN}"
+fi
+
+### Prerequisites
+
+# TODO: Try to not access the GitHub REST API, because it can get throttled.
+if [ -n "$(command -v curl 2> /dev/null)" ]; then
+  GET_URL_TO_STDOUT="curl ${auth_header_option} -s"
+elif [ -n "$(command -v wget 2> /dev/null)" ]; then
+  GET_URL_TO_STDOUT="wget ${auth_header_option} -q -O -"
+else
+  echo "echo Neither curl nor wget is installed"
+  exit 2
+fi
+if [ -z "$(command -v jq 2> /dev/null)" ]; then
+  echo "echo jq is not installed"
+  exit 2
+fi
+
 ### Functions
 
 # Returns either `git rev-parse HEAD^1` if HEAD^1 exists, or `git rev-parse HEAD`.
@@ -99,16 +136,6 @@ head1() {
   fi
 }
 
-### Variables
-
-# "GITHUB_PAT" is a GitHub Personal Access Token.
-auth_header_option=()
-if [ -n "$GITHUB_PAT" ]; then
-  auth_header_option=(--header="Authorization: token ${GITHUB_PAT}")
-elif [ -n "$GH_TOKEN" ]; then
-  auth_header_option=(--header="Authorization: token ${GH_TOKEN}")
-fi
-
 ### Organization
 
 ## Continuous integration services
@@ -118,24 +145,21 @@ if [ "$TRAVIS" = "true" ]; then
     CI_ORGANIZATION=${TRAVIS_REPO_SLUG%/*}
   fi
 elif [ -n "$AZURE_HTTP_USER_AGENT" ]; then
+  # TODO: Can I implement this without a GitHub API request?
   if [ "$BUILD_REASON" = "PullRequest" ]; then
     url="https://api.github.com/repos/${BUILD_REPOSITORY_NAME}/pulls/${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}"
-    SLUG=$(wget -q "${auth_header_option[@]}" -O - "${url}" | jq .head.label | sed 's/"//g')
+    pull_json="$(${GET_URL_TO_STDOUT} "${url}" 2>&1 | tr -d '[:cntrl:]')"
+    SLUG=$(printf '%s' "${pull_json}" | jq .head.label | sed 's/"//g')
     if [ -z "$SLUG" ]; then
-      sleep 5
-      SLUG=$(wget -q "${auth_header_option[@]}" -O - "${url}" | jq .head.label | sed 's/"//g')
-      if [ -z "$SLUG" ]; then
-        wget_output="$(wget "${auth_header_option[@]}" -O - "${url}" 2>&1)" || true
-        echo "echo ${SCRIPT_NAME} error: bad output for wget -O - ${url}"
-        if [ -n "${auth_header_option[*]}" ]; then
-          echo "echo auth_header_option is set."
-        fi
-        echo "echo ---- start of wget output ----"
-        # shellcheck disable=SC2001
-        echo "${wget_output}" | sed -e 's/^/echo /'
-        echo "echo ---- end of wget output ----"
-        exit 2
+      echo "echo ${SCRIPT_NAME} error: bad output for ${url}"
+      if [ -n "${auth_header_option}" ]; then
+        echo "echo auth_header_option is set."
       fi
+      echo "echo ---- start of wget output ----"
+      # shellcheck disable=SC2001
+      printf '%s' "${pull_json}" | sed -e 's/^/echo /'
+      echo "echo ---- end of wget output ----"
+      exit 2
     fi
     CI_ORGANIZATION=${SLUG%:*}
   else
@@ -147,25 +171,14 @@ elif [ -n "$CIRCLE_PR_USERNAME" ]; then
 elif [ -n "$GITHUB_HEAD_REF" ]; then
   # GitHub Actions pull request
 
-  if [ -n "$(command -v curl 2> /dev/null)" ]; then
-    GET_URL_TO_STDOUT="curl -s"
-  elif [ -n "$(command -v wget 2> /dev/null)" ]; then
-    GET_URL_TO_STDOUT="wget -q -O -"
-  else
-    echo "echo Neither curl nor wget is installed"
-    exit 2
-  fi
-  if [ -z "$(command -v jq 2> /dev/null)" ]; then
-    echo "echo jq is not installed"
-    exit 2
-  fi
-
+  # TODO: Can I implement this without a GitHub API request?
+  # Is GITHUB_ACTOR equal to CI_ORGANIZATION, maybe??  (Need to observe beyond mernst.)
   GITHUB_PR_NUMBER=${GITHUB_REF_NAME%/merge}
-  CI_ORGANIZATION=$(${GET_URL_TO_STDOUT} \
-    "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}" \
-    | jq '.head.repo.owner.login')
+  url="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}"
+  pull_json="$(${GET_URL_TO_STDOUT} "${url}" 2>&1 | tr -d '[:cntrl:]')"
+  CI_ORGANIZATION=$(printf '%s' "${pull_json}" | jq '.head.repo.owner.login')
   if [ "$DEBUG" = "--debug" ]; then
-    echo "echo GitHub Actions pull request"
+    echo "echo GitHub Actions pull request, GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
     echo "echo GITHUB_PR_NUMBER=${GITHUB_PR_NUMBER}"
     echo "echo CI_ORGANIZATION=${CI_ORGANIZATION}"
   fi
@@ -185,7 +198,7 @@ fi
 
 ## Default
 if [ -z "$CI_ORGANIZATION" ]; then
-  CI_ORGANIZATION=$1
+  CI_ORGANIZATION="${DEFAULT_ORGANIZATION}"
 fi
 
 if [ "$DEBUG" = "--debug" ]; then
@@ -213,10 +226,9 @@ if [ -n "$SYSTEM_PULLREQUEST_TARGETBRANCH" ]; then
   if [ "$DEBUG" = "--debug" ]; then
     echo "echo Azure Pipelines pull request $SYSTEM_PULLREQUEST_TARGETBRANCH;"
   fi
-  CI_IS_PULL_REQUEST=true
   # WARNING!  $BUILD_SOURCEBRANCHNAME is just a name, not a full ref path.  For example,
   # $BUILD_SOURCEBRANCHNAME may be "merge" when $BUILD_SOURCEBRANCH is "refs/pull/2971/merge".
-  CI_BRANCH_NAME=$SYSTEM_PULLREQUEST_SOURCEBRANCH
+  CI_BRANCH=$SYSTEM_PULLREQUEST_SOURCEBRANCH
   # For CI_COMMIT_RANGE_START:  HEAD = $BUILD_SOURCEVERSION is a commit created by Azure; it isn't
   # in the repo.  Its first child HEAD^1 is the target branch (e.g., master); use that instead of
   # $SYSTEM_PULLREQUEST_TARGETBRANCH is not fetched into this repo.
@@ -229,11 +241,10 @@ elif [ -n "$BUILD_SOURCEBRANCH" ]; then
     echo "echo Azure Pipelines build for a branch $BUILD_SOURCEBRANCH;"
     echo "echo SYSTEM_PULLREQUEST_TARGETBRANCH=$SYSTEM_PULLREQUEST_TARGETBRANCH is not set but BUILD_SOURCEBRANCH=$BUILD_SOURCEBRANCH;"
   fi
-  CI_IS_PULL_REQUEST=false
   # In Azure Pipelines:  BUILD_SOURCEBRANCH is a full ref path like "refs/heads/mybranch";
   # BUILD_SOURCEBRANCHNAME is a short name like "mybranch"; $BUILD_SOURCEVERSION is a commit ID.
   # some clients such as `git-clone-related` MUST be given a branch name, not a commit ID.
-  CI_BRANCH_NAME=$BUILD_SOURCEBRANCHNAME
+  CI_BRANCH=$BUILD_SOURCEBRANCHNAME
   if [ "$BUILD_SOURCEBRANCHNAME" = "$DEFAULT_BRANCH_NAME" ]; then
     DEFAULT_CI_COMMIT_RANGE_START=$(head1)
 
@@ -288,43 +299,26 @@ elif [ "$TRAVIS" = "true" ]; then
   if [ "$DEBUG" = "--debug" ]; then
     echo "echo Travis CI $TRAVIS;"
   fi
-  CI_IS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
-  CI_BRANCH_NAME=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
+  CI_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
   if [ "$VERBOSE" = "--verbose" ]; then
     echo "echo TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH;"
     echo "echo TRAVIS_BRANCH=$TRAVIS_BRANCH;"
-    echo "echo CI_BRANCH_NAME=$CI_BRANCH_NAME;"
+    echo "echo CI_BRANCH=$CI_BRANCH;"
   fi
   # $TRAVIS_COMMIT_RANGE is empty for builds triggered by the initial commit of a new branch.
   CI_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
 
 elif [ -n "$CIRCLECI" ]; then
-  if [ -n "$CIRCLE_PULL_REQUEST" ]; then
-    CI_IS_PULL_REQUEST=true
-  else
-    CI_IS_PULL_REQUEST=false
-  fi
   if [ "$DEBUG" = "--debug" ]; then
-    echo "echo CircleCI; CI_IS_PULL_REQUEST=$CI_IS_PULL_REQUEST;"
+    echo "echo CircleCI, CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST;"
   fi
   if [ -n "$CIRCLE_PR_NUMBER" ]; then
-    if [ -n "$(command -v curl 2> /dev/null)" ]; then
-      GET_URL_TO_STDOUT="curl -s"
-    elif [ -n "$(command -v wget 2> /dev/null)" ]; then
-      GET_URL_TO_STDOUT="wget -q -O -"
-    else
-      echo "echo Neither curl nor wget is installed"
-      exit 2
-    fi
-    if [ -z "$(command -v jq 2> /dev/null)" ]; then
-      echo "echo jq is not installed"
-      exit 2
-    fi
-
-    pull_details="$($GET_URL_TO_STDOUT "${auth_header_option[@]}" "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER}")"
-    CI_BRANCH_NAME=$(echo "${pull_details}" | jq -r '.head.ref')
-    CI_COMMIT_RANGE_START=$(echo "${pull_details}" | jq -r '.base.sha')
-    CI_COMMIT_RANGE_END=$(echo "${pull_details}" | jq -r '.head.sha')
+    # TODO: Can I implement this without a GitHub API request?
+    url="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER}"
+    pull_json="$(${GET_URL_TO_STDOUT} "${url}" | tr -d '[:cntrl:]')"
+    CI_BRANCH=$(printf '%s' "${pull_json}" | jq -r '.head.ref')
+    CI_COMMIT_RANGE_START=$(printf '%s' "${pull_json}" | jq -r '.base.sha')
+    CI_COMMIT_RANGE_END=$(printf '%s' "${pull_json}" | jq -r '.head.sha')
     CI_COMMIT_RANGE="${CI_COMMIT_RANGE_START}...${CI_COMMIT_RANGE_END}"
 
     if ! git rev-parse --verify -q "${CI_COMMIT_RANGE_START}^{commit}" > /dev/null; then
@@ -338,7 +332,7 @@ elif [ -n "$CIRCLECI" ]; then
       fi
     fi
   else
-    CI_BRANCH_NAME=$CIRCLE_BRANCH
+    CI_BRANCH=$CIRCLE_BRANCH
   fi
 
 elif [ -n "${GITHUB_HEAD_REF}" ]; then
@@ -357,14 +351,13 @@ elif [ -n "${GITHUB_HEAD_REF}" ]; then
 
   GITHUB_PR_NUMBER=${GITHUB_REF_NAME%/merge}
 
-  CI_IS_PULL_REQUEST=true
-  CI_BRANCH_NAME="${GITHUB_HEAD_REF}"
+  CI_BRANCH="${GITHUB_HEAD_REF}"
   if ! CI_COMMIT_RANGE_START=$(git rev-parse "${GITHUB_BASE_REF}" 2> /dev/null); then
     if ! CI_COMMIT_RANGE_START=$(git rev-parse remotes/origin/"${GITHUB_BASE_REF}" 2> /dev/null); then
       if ! CI_COMMIT_RANGE_START=$(git rev-parse refs/remotes/origin/"${GITHUB_BASE_REF}" 2> /dev/null); then
         if ! CI_COMMIT_RANGE_START=$(git rev-parse refs/remotes/origin/"${DEFAULT_BRANCH_NAME}" 2> /dev/null); then
-          pull_details="$($GET_URL_TO_STDOUT "${auth_header_option[@]}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}")"
-          if ! CI_COMMIT_RANGE_START=$(echo "${pull_details}" | jq -r '.base.sha'); then
+          pull_json="$($GET_URL_TO_STDOUT "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}" | tr -d '[:cntrl:]')"
+          if ! CI_COMMIT_RANGE_START=$(printf '%s' "${pull_json}" | jq -r '.base.sha'); then
             echo "echo ${SCRIPT_NAME} in $(pwd): cannot find commit range start, tried ${GITHUB_BASE_REF} and remotes/origin/${GITHUB_BASE_REF} and refs/remotes/origin/${GITHUB_BASE_REF} and refs/remotes/origin/${DEFAULT_BRANCH_NAME}"
             echo 'echo ---------------- start of set'
             set | sed -e 's/^/echo /'
@@ -400,12 +393,14 @@ elif [ -n "$GITHUB_ACTIONS" ]; then
     exit 2
   fi
 
-  CI_IS_PULL_REQUEST=false
-  # GITHUB_REF_NAME may be, for example, "40/merge".
-  if [[ -n $(git branch --list branch-name) ]]; then
-    CI_BRANCH_NAME="${GITHUB_REF_NAME}"
+  # GITHUB_REF_NAME may be a branch name or "40/merge".
+  if [ -n "$(git branch --list "${GITHUB_REF_NAME}")" ]; then
+    CI_BRANCH="${GITHUB_REF_NAME}"
   else
-    CI_BRANCH_NAME="NEEDED"
+    # TODO: Can I implement this without a GitHub API request?
+    url="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER}"
+    pull_json="$(${GET_URL_TO_STDOUT} "${url}" | tr -d '[:cntrl:]')"
+    CI_BRANCH=$(printf '%s' "${pull_json}" | jq -r '.head.ref')
   fi
   CI_COMMIT_RANGE_END="${GITHUB_SHA}"
 
@@ -414,20 +409,18 @@ else
   if [ "$DEBUG" = "--debug" ]; then
     echo "echo Else clause: no CI environment detected;"
   fi
-  CI_IS_PULL_REQUEST=false
   # git 2.22 and later has `git branch --show-current`; CircleCI doesn't have that version yet.
-  CI_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
+  CI_BRANCH=$(git rev-parse --abbrev-ref HEAD)
   # In an Azure Pipelines pull request, `git branch` yields "(HEAD detached at pull/4/merge)".
   # If you re-run a pull request via "Queue" rather than "Rebuild",
   # variables SYSTEM_PULLREQUEST_TARGETBRANCH and SYSTEM_PULLREQUEST_SOURCEBRANCH are not set.
-  if [ "$CI_BRANCH_NAME" = '(HEAD' ]; then
-    CI_BRANCH_NAME=$DEFAULT_BRANCH_NAME
+  if [ "$CI_BRANCH" = '(HEAD' ]; then
+    CI_BRANCH=$DEFAULT_BRANCH_NAME
   fi
 fi
 
 if [ "$DEBUG" = "--debug" ]; then
-  echo "echo CI_IS_PULL_REQUEST=${CI_IS_PULL_REQUEST};"
-  echo "echo CI_BRANCH_NAME=${CI_BRANCH_NAME};"
+  echo "echo CI_BRANCH=${CI_BRANCH};"
   echo "echo CI_COMMIT_RANGE_START=${CI_COMMIT_RANGE_START};"
   echo "echo CI_COMMIT_RANGE_END=${CI_COMMIT_RANGE_END};"
   echo "echo CI_COMMIT_RANGE=${CI_COMMIT_RANGE};"
@@ -438,9 +431,9 @@ fi
 # Separate from "It's not a pull request" because sometimes this is not set for Travis.
 if [ -z "$CI_COMMIT_RANGE" ]; then
   if [ "$DEBUG" = "--debug" ]; then
-    echo "echo Setting CI_COMMIT_RANGE from CI_BRANCH_NAME=$CI_BRANCH_NAME;"
+    echo "echo Setting CI_COMMIT_RANGE from CI_BRANCH=$CI_BRANCH;"
   fi
-  if [ "$CI_BRANCH_NAME" = "$DEFAULT_BRANCH_NAME" ]; then
+  if [ "$CI_BRANCH" = "$DEFAULT_BRANCH_NAME" ]; then
     if git show --summary HEAD | grep -q ^Merge:; then
       CI_COMMIT_RANGE_START=$(git merge-base HEAD^1 HEAD^2)
     else
@@ -450,6 +443,9 @@ if [ -z "$CI_COMMIT_RANGE" ]; then
   else
     if git rev-parse --verify --quiet "origin/$DEFAULT_BRANCH_NAME" > /dev/null 2>&1; then
       CI_COMMIT_RANGE_START=$(git rev-parse "origin/$DEFAULT_BRANCH_NAME")
+      if [ "$DEBUG" = "--debug" ]; then
+        echo "echo Set CI_COMMIT_START=$CI_COMMIT_START from git rev-parse origin/$DEFAULT_BRANCH_NAME;"
+      fi
     else
       if git show --summary HEAD | grep -q ^Merge:; then
         CI_COMMIT_RANGE_START=$(git merge-base HEAD^1 HEAD^2)
@@ -457,9 +453,15 @@ if [ -z "$CI_COMMIT_RANGE" ]; then
         CI_COMMIT_RANGE_START=$(head1)
       fi
     fi
-    CI_COMMIT_RANGE_END=$(git rev-parse "$CI_BRANCH_NAME")
+    CI_COMMIT_RANGE_END=$(git rev-parse "$CI_BRANCH")
   fi
   CI_COMMIT_RANGE=${CI_COMMIT_RANGE_START}...${CI_COMMIT_RANGE_END}
+  if [ "$DEBUG" = "--debug" ]; then
+    echo "echo CI_BRANCH=${CI_BRANCH};"
+    echo "echo CI_COMMIT_RANGE_START=${CI_COMMIT_RANGE_START};"
+    echo "echo CI_COMMIT_RANGE_END=${CI_COMMIT_RANGE_END};"
+    echo "echo CI_COMMIT_RANGE=${CI_COMMIT_RANGE};"
+  fi
 fi
 
 if [ -z "$CI_COMMIT_RANGE_START" ]; then
@@ -490,6 +492,20 @@ if [ "$CI_COMMIT_RANGE_START" = "$CI_COMMIT_RANGE_END" ]; then
   CI_COMMIT_RANGE="${CI_COMMIT_RANGE_START}...${CI_COMMIT_RANGE_END}"
 fi
 
+if [ "$VERBOSE" = "--verbose" ]; then
+  if [ -n "${pull_json}" ]; then
+    echo "echo CI_ACCESSED_GITHUB_API=true;"
+  else
+    echo "echo CI_ACCESSED_GITHUB_API=false;"
+  fi
+fi
+
+if [ "$VERBOSE" = "--verbose" ]; then
+  echo 'echo ---------------- start of first 10000 lines of diff:'
+  git --no-pager diff "${CI_COMMIT_RANGE}" | head --lines=10000 | sed -e 's/^/echo "echo /' -e 's/$/"/'
+  echo 'echo ---------------- end of first 10000 lines of diff.'
+fi
+
 # The diff might be empty if the last commit is the revert of the one before it.
 
 ### Print it out
@@ -499,13 +515,9 @@ if [ "$VERBOSE" = "--verbose" ]; then
 fi
 echo "CI_ORGANIZATION=$CI_ORGANIZATION; export CI_ORGANIZATION;"
 if [ "$VERBOSE" = "--verbose" ]; then
-  echo "echo CI_IS_PULL_REQUEST=$CI_IS_PULL_REQUEST;"
+  echo "echo CI_BRANCH=$CI_BRANCH;"
 fi
-echo "CI_IS_PULL_REQUEST=$CI_IS_PULL_REQUEST; export CI_IS_PULL_REQUEST;"
-if [ "$VERBOSE" = "--verbose" ]; then
-  echo "echo CI_BRANCH_NAME=$CI_BRANCH_NAME;"
-fi
-echo "CI_BRANCH_NAME=$CI_BRANCH_NAME; export CI_BRANCH_NAME;"
+echo "CI_BRANCH=$CI_BRANCH; export CI_BRANCH;"
 if [ "$VERBOSE" = "--verbose" ]; then
   echo "echo CI_COMMIT_RANGE_START=$CI_COMMIT_RANGE_START;"
 fi
