Pull origin if needed under CircleCI

diff --git a/ci-info b/ci-info
--- a/ci-info
+++ b/ci-info
@@ -65,6 +65,10 @@ if [ "$DEBUG" = "--debug" ]; then
   set | sed -e 's/^/echo /'
   echo 'echo ---------------- end of set'
   echo
+  echo 'echo ---------------- start of git status'
+  git --no-pager status | sed -e 's/^/echo /'
+  echo 'echo ---------------- end of git status'
+  echo
   echo 'echo ---------------- start of all branches'
   git --no-pager branch -a | sed -e 's/^/echo /'
   echo 'echo ---------------- end of all branches'
@@ -318,6 +322,17 @@ elif [ -n "$CIRCLECI" ]; then
     CI_COMMIT_RANGE_START=$(echo "${pull_details}" | jq -r '.base.sha')
     CI_COMMIT_RANGE_END=$(echo "${pull_details}" | jq -r '.head.sha')
     CI_COMMIT_RANGE="${CI_COMMIT_RANGE_START}...${CI_COMMIT_RANGE_END}"
+
+    if ! git rev-parse --verify -q "${CI_COMMIT_RANGE_START}^{commit}" > /dev/null; then
+      git fetch --depth=25 origin
+      if ! git rev-parse --verify -q "${CI_COMMIT_RANGE_START}^{commit}" > /dev/null; then
+        git fetch --unshallow origin
+        if ! git rev-parse --verify -q "${CI_COMMIT_RANGE_START}^{commit}" > /dev/null; then
+          echo "echo cannot find commit range start ${CI_COMMIT_RANGE_START} in origin"
+          exit 2
+        fi
+      fi
+    fi
   else
     CI_BRANCH_NAME=$CIRCLE_BRANCH
   fi
