New `ci-last-success.py` script, used by `ci-info`

diff --git a/ci-info b/ci-info
--- a/ci-info
+++ b/ci-info
@@ -37,6 +37,8 @@ if [ "$#" -gt 1 ] ; then
   exit 2
 fi
 
+SCRIPTDIR="$( cd "$(dirname "$0")" ; pwd -P )"
+
 if [ "$DEBUG" = "--debug" ] ; then
   echo
   env | sort | sed -e 's/^/echo /'
@@ -62,6 +64,7 @@ elif [ -n "$AZURE_HTTP_USER_AGENT" ]; then
     CI_ORGANIZATION=${SLUG%:*}
   else
     CI_ORGANIZATION=${BUILD_REPOSITORY_NAME%/*}
+    CI_REPO=${BUILD_REPOSITORY_NAME##*/}
   fi
 fi
 
@@ -102,9 +105,20 @@ elif [ -n "$BUILD_SOURCEBRANCH" ] ; then
   # some clients such as `git-clone-related` MUST be given a branch name, not a commit ID.
   CI_BRANCH_NAME=$BUILD_SOURCEBRANCHNAME
   if [ "$BUILD_SOURCEBRANCHNAME" = "master" ] ; then
-    # This isn't right, because there could have been multiple pushes since the
-    # last finished/successful CI job.
-    CI_COMMIT_RANGE_START=`git rev-parse HEAD^1`
+    # `git rev-parse HEAD^1` isn't right, because there could have been
+    # multiple pushes since the last successful CI job.  But use it if we
+    # cannot run the `ci-last-success.py` script.
+    if pip3 list | tail -n +1 | grep -q '^requests ' ; then
+      echo "Python requests package is already installed"
+    else
+      sudo pip3 install requests || pip3 install --user requests || true
+    fi
+    if pip3 list | tail -n +1 | grep -q '^requests ' ; then
+      CI_COMMIT_RANGE_START=`${SCRIPTDIR}/ci-last-success.py ${CI_ORGANIZATION} ${CI_REPO}`
+    else
+      echo "WARNING: Could not run ci-last-success.py script; just considering last commit."
+      CI_COMMIT_RANGE_START=`git rev-parse HEAD^1`
+    fi
   else
     git fetch origin master
     CI_COMMIT_RANGE_START=`git rev-parse origin/master`
