Enable more diagnostics

diff --git a/ci-lint-diff b/ci-lint-diff
--- a/ci-lint-diff
+++ b/ci-lint-diff
@@ -51,12 +51,10 @@ eval `${SCRIPTDIR}/ci-info`
 
 # Ensure the commits mentioned in $CI_COMMIT_RANGE are available.
 if [ "$(git cat-file -t $CI_COMMIT_RANGE_START)" != "commit" ] ; then
-  echo "Commit CI_COMMIT_RANGE_START=$CI_COMMIT_RANGE_START not found; clone more deeply."
-  CI_LINT_DIFF_ERROR=1
+  CI_LINT_DIFF_ERROR="Commit CI_COMMIT_RANGE_START=$CI_COMMIT_RANGE_START not found; clone more deeply."
 fi
 if [ "$(git cat-file -t $CI_COMMIT_RANGE_END)" != "commit" ] ; then
-  echo "Commit CI_COMMIT_RANGE_END=$CI_COMMIT_RANGE_END not found; clone more deeply."
-  CI_LINT_DIFF_ERROR=1
+  CI_LINT_DIFF_ERROR="Commit CI_COMMIT_RANGE_END=$CI_COMMIT_RANGE_END not found; clone more deeply."
 fi
 
 set +e
@@ -65,27 +63,24 @@ echo "git diff $CI_COMMIT_RANGE > /tmp/diff.txt"
 git --no-pager diff --exit-code $CI_COMMIT_RANGE > /tmp/diff.txt 2>&1
 git_status=$?
 if [ $git_status -gt 1 ] ; then
-  echo "git diff exited with status $git_status"
+  CI_LINT_DIFF_ERROR="git diff exited with status $git_status"
   cat /tmp/diff.txt
   git --no-pager diff --exit-code $CI_COMMIT_RANGE
   git --no-pager branch -a
   git --no-pager diff $CI_COMMIT_RANGE
-  exit 2
-fi
-set -e
-if [ ! -r /tmp/diff.txt ] ; then
-  echo "/tmp/diff.txt does not exist"
-  exit 2
+elif [ ! -r /tmp/diff.txt ] ; then
+  CI_LINT_DIFF_ERROR="/tmp/diff.txt does not exist"
 fi
 if [ ! -s /tmp/diff.txt ] ; then
-  echo
-  echo "*****"
-  echo "ERROR: /tmp/diff.txt is empty for $CI_COMMIT_RANGE ."
-  echo "Try pulling base branch (often master) into compare branch (often your feature branch)."
-  CI_LINT_DIFF_ERROR=1
+  CI_LINT_DIFF_ERROR="ERROR: Empty diff for $CI_COMMIT_RANGE. Try pulling base branch (often master) into compare branch (often your feature branch)."
 fi
 
 if [ -n $CI_LINT_DIFF_ERROR ] ; then
+  echo
+  echo "*****"
+  echo "$CI_LINT_DIFF_ERROR"
+  echo "*****"
+  echo 
   echo "This command will print diagnostic information, then exit."
   echo
   echo ${SCRIPTDIR}/ci-info --debug
@@ -142,6 +137,10 @@ if [ -n $CI_LINT_DIFF_ERROR ] ; then
   echo
   echo "Environment:"
   env | sort
+  echo
+  echo "*****"
+  echo "$CI_LINT_DIFF_ERROR"
+  echo "*****"
   exit 2
 fi
 
@@ -153,5 +152,7 @@ if [ "$DEBUG" = "--debug" ] ; then
     cat /tmp/diff.txt
     echo "end of /tmp/diff.txt file."
 fi
+
+set -e
 
 python ${SCRIPTDIR}/lint-diff.py $DEBUG --guess-strip /tmp/diff.txt $WARNINGSFILE
