Diagnostics about commits that are not available

diff --git a/ci-lint-diff b/ci-lint-diff
--- a/ci-lint-diff
+++ b/ci-lint-diff
@@ -60,7 +60,7 @@ if [ "$CI_COMMIT_RANGE_START_TYPE" != "commit" ]; then
     if ! git show-ref --verify --quiet refs/heads/$CI_COMMIT_RANGE_START > /dev/null 2>&1; then
       echo git branch --track $CI_COMMIT_RANGE_START origin/$CI_COMMIT_RANGE_START
       git branch --track $CI_COMMIT_RANGE_START origin/$CI_COMMIT_RANGE_START \
-	  || (git log --graph | head --lines=10000 && false)
+	  || (echo "Commit $CI_COMMIT_RANGE_START not found; clone more deeply." && false)
     fi
   fi
 fi
@@ -76,7 +76,7 @@ if [ "$CI_COMMIT_RANGE_END_TYPE" != "commit" ]; then
     if ! git show-ref --verify --quiet refs/heads/$CI_COMMIT_RANGE_END > /dev/null 2>&1; then
       echo git branch --track $CI_COMMIT_RANGE_END origin/$CI_COMMIT_RANGE_END
       git branch --track $CI_COMMIT_RANGE_END origin/$CI_COMMIT_RANGE_END \
-	  || (git log --graph | head --lines=10000 && false)
+	  || (echo "Commit $CI_COMMIT_RANGE_END not found; clone more deeply." && false)
     fi
   fi
 fi
