Reformat

diff --git a/cronic b/cronic
--- a/cronic
+++ b/cronic
@@ -21,21 +21,18 @@ ERR=/tmp/cronic.err.$$
 TRACE=/tmp/cronic.trace.$$
 
 EXPECTED=0
-if [ "$1" == "--expected-status" ]
-    then
-    shift
-    EXPECTED=$1
-    shift
+if [ "$1" == "--expected-status" ]; then
+  shift
+  EXPECTED=$1
+  shift
 fi
 PERMITSTDERR=0
-if [ "$1" == "--permit-stderr" ]
-  then
+if [ "$1" == "--permit-stderr" ]; then
   shift
   PERMITSTDERR=1
 fi
 DUPLICATE_STDERR=0
-if [ "$1" == "--duplicate-stderr" ]
-  then
+if [ "$1" == "--duplicate-stderr" ]; then
   shift
   DUPLICATE_STDERR=1
 fi
@@ -46,48 +43,42 @@ RESULT=$?
 set -e
 
 PATTERN="^${PS4:0:1}\\+${PS4:1}"
-if grep -q "$PATTERN" $TRACE
-then
-    grep -v "$PATTERN" $TRACE > $ERR
+if grep -q "$PATTERN" $TRACE; then
+  grep -v "$PATTERN" $TRACE >$ERR
 else
-    ERR=$TRACE
+  ERR=$TRACE
 fi
 
-if [ $RESULT -ne "$EXPECTED" ] || { [ $PERMITSTDERR -eq 0 ] && [ -s "$ERR" ]; }
-    then
-    echo "Cronic detected failure or error output for the command:"
-    echo "$@"
+if [ $RESULT -ne "$EXPECTED" ] || { [ $PERMITSTDERR -eq 0 ] && [ -s "$ERR" ]; }; then
+  echo "Cronic detected failure or error output for the command:"
+  echo "$@"
+  echo
+  if [[ $EXPECTED -eq 0 ]]; then
+    echo "RESULT CODE: $RESULT  (0 means success)"
+  else
+    echo "RESULT CODE: $RESULT  (expected: $EXPECTED)"
+  fi
+  echo
+  echo "ERROR OUTPUT:"
+  cat "$ERR"
+  echo
+  echo "STANDARD OUTPUT:"
+  cat "$OUT"
+  if [ $TRACE != $ERR ]; then
     echo
-    if [[ $EXPECTED -eq 0 ]]
-    then
-        echo "RESULT CODE: $RESULT  (0 means success)"
-    else
-        echo "RESULT CODE: $RESULT  (expected: $EXPECTED)"
-    fi
+    echo "TRACE-ERROR OUTPUT:"
+    cat "$TRACE"
+  fi
+  if [ $DUPLICATE_STDERR -eq 1 ]; then
     echo
     echo "ERROR OUTPUT:"
     cat "$ERR"
-    echo
-    echo "STANDARD OUTPUT:"
-    cat "$OUT"
-    if [ $TRACE != $ERR ]
-    then
-        echo
-        echo "TRACE-ERROR OUTPUT:"
-        cat "$TRACE"
-    fi
-    if [ $DUPLICATE_STDERR -eq 1 ]
-    then
-        echo
-        echo "ERROR OUTPUT:"
-        cat "$ERR"
-    fi
+  fi
 fi
 
 rm -f "$OUT"
-if [ ! $ERR == /dev/null ]
-    then
-    rm -f "$ERR"
+if [ ! $ERR == /dev/null ]; then
+  rm -f "$ERR"
 fi
 rm -f "$TRACE"
 exit $RESULT
