Reformat

diff --git a/ediff-merge-script b/ediff-merge-script
--- a/ediff-merge-script
+++ b/ediff-merge-script
@@ -24,19 +24,17 @@ echo "which is an obsolete version from https://github.com/plume-lib/plume-scrip
 _EMACSCLIENT=emacs
 # _EMACSCLIENT=emacsclient
 
-
 # This script is originally from
 #   http://stackoverflow.com/questions/1817370/using-ediff-as-git-mergetool
 # I have extended so it handles both emacs and emacsclient,
 # and made other improvements.
 
-
 # test args
 if [ ! ${#} -ge 3 ]; then
-    echo 1>&2 "Error: ${0} requires 4 arguments, got ${#}"
-    echo 1>&2 "Usage: ${0} LOCAL REMOTE MERGED BASE"
-    echo 1>&2 "       (LOCAL, REMOTE, MERGED, BASE can be provided by \`git mergetool'.)"
-    exit 1
+  echo 1>&2 "Error: ${0} requires 4 arguments, got ${#}"
+  echo 1>&2 "Usage: ${0} LOCAL REMOTE MERGED BASE"
+  echo 1>&2 "       (LOCAL, REMOTE, MERGED, BASE can be provided by \`git mergetool'.)"
+  exit 1
 fi
 
 # tools
@@ -49,13 +47,13 @@ _MKTEMP="/bin/mktemp"
 _LOCAL=${1}
 _REMOTE=${2}
 _MERGED=${3}
-if [ -r "${4}" ] ; then
-    _BASE=${4}
-    _EDIFF=ediff-merge-files-with-ancestor
-    _EVAL="(${_EDIFF} \"${_LOCAL}\" \"${_REMOTE}\" \"${_BASE}\" nil \"${_MERGED}\")"
+if [ -r "${4}" ]; then
+  _BASE=${4}
+  _EDIFF=ediff-merge-files-with-ancestor
+  _EVAL="(${_EDIFF} \"${_LOCAL}\" \"${_REMOTE}\" \"${_BASE}\" nil \"${_MERGED}\")"
 else
-    _EDIFF=ediff-merge-files
-    _EVAL="(${_EDIFF} \"${_LOCAL}\" \"${_REMOTE}\" nil \"${_MERGED}\")"
+  _EDIFF=ediff-merge-files
+  _EVAL="(${_EDIFF} \"${_LOCAL}\" \"${_REMOTE}\" nil \"${_MERGED}\")"
 fi
 
 _EVAL_PREFIX="(defun ediff-write-merge-buffer ()\
@@ -70,10 +68,10 @@ if [[ $_EMACSCLIENT == *"emacsclient"* ]]; then
   ## emacsclient only, not emacs
   # console vs. X
   if [ "${TERM}" = "linux" ]; then
-      unset DISPLAY
-      _EMACSCLIENTOPTS='-t -a \"\"'
+    unset DISPLAY
+    _EMACSCLIENTOPTS='-t -a \"\"'
   else
-      _EMACSCLIENTOPTS="-c -a \"\""
+    _EMACSCLIENTOPTS="-c -a \"\""
   fi
 else
   ## emacs only, not emacsclient
@@ -85,15 +83,14 @@ fi
 # echo "${_EMACSCLIENT}" "${_EMACSCLIENTOPTS}" --eval "(progn ${_EVAL_PREFIX} ${_EVAL_PREFIX2} ${_EVAL})"
 "${_EMACSCLIENT}" "${_EMACSCLIENTOPTS}" --eval "(progn ${_EVAL_PREFIX} ${_EVAL_PREFIX2} ${_EVAL})" 2>&1
 
-
 # check modified file
 if [ ! "$("${_EGREP}" -c '^(<<<<<<<|=======|>>>>>>>|####### Ancestor)$' "${_MERGED}")" = 0 ]; then
-    _MERGEDSAVE=$(${_MKTEMP} --tmpdir "$(${_BASENAME} "${_MERGED}").XXXXXXXXXX")
-    ${_CP} "${_MERGED}" "${_MERGEDSAVE}"
-    echo 1>&2 "Oops! Conflict markers detected in $_MERGED."
-    echo 1>&2 "Saved your changes to ${_MERGEDSAVE}"
-    echo 1>&2 "Exiting with code 1."
-    exit 1
+  _MERGEDSAVE=$(${_MKTEMP} --tmpdir "$(${_BASENAME} "${_MERGED}").XXXXXXXXXX")
+  ${_CP} "${_MERGED}" "${_MERGEDSAVE}"
+  echo 1>&2 "Oops! Conflict markers detected in $_MERGED."
+  echo 1>&2 "Saved your changes to ${_MERGEDSAVE}"
+  echo 1>&2 "Exiting with code 1."
+  exit 1
 fi
 
 # It would not be appropriate for this script to do the merge, because
diff --git a/git-find-fork b/git-find-fork
--- a/git-find-fork
+++ b/git-find-fork
@@ -18,10 +18,10 @@ echo "which is an obsolete version from https://github.com/plume-lib/plume-scrip
 # Often, you can use the `git-clone-related` script instead of this one.
 
 if [ "$#" -ne 3 ]; then
-    script=$(basename -- "$0")
-    >&2 echo "Error: $script requires 3 arguments, got $#"
-    >&2 echo "Usage: $script ORG UPSTREAM_ORG REPONAME"
-    exit 1
+  script=$(basename -- "$0")
+  echo >&2 "Error: $script requires 3 arguments, got $#"
+  echo >&2 "Usage: $script ORG UPSTREAM_ORG REPONAME"
+  exit 1
 fi
 
 ORG=$1
@@ -33,10 +33,9 @@ REPONAME=$3
 # export GITEXISTS="git ls-remote"
 export GITEXISTS="wget -q --spider"
 
-
-if ( ${GITEXISTS} "https://github.com/${ORG}/${REPONAME}.git" > /dev/null ); then
-   OWNER="${ORG}"
+if (${GITEXISTS} "https://github.com/${ORG}/${REPONAME}.git" >/dev/null); then
+  OWNER="${ORG}"
 else
-   OWNER="${UPSTREAM_ORG}"
+  OWNER="${UPSTREAM_ORG}"
 fi
 echo "https://github.com/${OWNER}/${REPONAME}.git"
