Add --fallback-branch command-line argument

diff --git a/git-clone-related b/git-clone-related
--- a/git-clone-related
+++ b/git-clone-related
@@ -8,7 +8,11 @@
 # clones the other, attempting to find a matching fork and branch.
 # This script also works in an Azure Pipelines, CircleCI, or Travis CI job.
 #
-# Usage:  git-clone-related [--debug] UPSTREAM_ORG REPO_NAME [DESTINATION] [GIT_CLONE_ARGS...]
+# Usage:  git-clone-related [ARGS] UPSTREAM_ORG REPO_NAME [DESTINATION] [GIT_CLONE_ARGS...]
+#   ARGS are:
+#     --upstream-branch FALLBACK_BRANCH
+#           the fallback branch name on the upstream repository; default "master"
+#     --debug                     print logging information
 #   UPSTREAM_ORG is, if this is a fork, the parent organization.
 #   REPO_NAME is the repository name without the organization.
 #   DESTINATION is the new clone (not its parent), by default ../REPO_NAME .
@@ -22,7 +26,7 @@
 # this script chooses the first of these that exists:
 #   branch ${MYBRANCH} of https://github.com/${MYORG}/${REPO_NAME}.git
 #   branch ${MYBRANCH} of https://github.com/${UPSTREAM_ORG}/${REPO_NAME}.git
-#   branch master of https://github.com/${UPSTREAM_ORG}/${REPO_NAME}.git
+#   branch ${FALLBACK_BRANCH} of https://github.com/${UPSTREAM_ORG}/${REPO_NAME}.git
 #
 # Requires the `jq` program to be installed, when used in Azure Pipelines jobs.
 
@@ -33,6 +37,13 @@ if [ "$1" = "--debug" ] ; then
   DEBUG=1
   shift
   set +x
+fi
+
+FALLBACK_BRANCH=master
+if [ "$1" = "--upstream-branch" ] ; then
+  shift
+  FALLBACK_BRANCH=$1
+  shift
 fi
 
 if [ "$#" -lt 2 ]; then
@@ -95,13 +106,18 @@ else
   if [ -n "$DEBUG" ] ; then
     echo "About to run git-find-branch" "${REPO_URL}" "${CI_BRANCH_NAME}" "${FALLBACK_BRANCH}"
   fi
-  REPO_BRANCH=$("${SCRIPTDIR}"/git-find-branch "${REPO_URL}" "${CI_BRANCH_NAME}")
+  REPO_BRANCH=$("${SCRIPTDIR}"/git-find-branch "${REPO_URL}" "${CI_BRANCH_NAME}" "${FALLBACK_BRANCH}")
   if [ -n "$DEBUG" ] ; then
     echo "git-find-branch ${REPO_URL} ${CI_BRANCH_NAME} => ${REPO_BRANCH}"
   fi
   if [ "$UPSTREAM_REPO_URL" != "$REPO_URL" ] && [ "$REPO_BRANCH" != "$CI_BRANCH_NAME" ] ; then
-    ## Don't use branch master of the downstream repo
+    ## Don't use the fallback branch (e.g., master) of the downstream repo
     REPO_URL="$UPSTREAM_REPO_URL"
+    REPO_BRANCH=$("${SCRIPTDIR}"/git-find-branch "${REPO_URL}" "${CI_BRANCH_NAME}" "${FALLBACK_BRANCH}")
+    if [ "$REPO_BRANCH" = "master" ] && [ "${FALLBACK_BRANCH}" != "master" ] ; then
+      echo "Error in git-clone-related: fallback branch ${FALLBACK_BRANCH} does not exist in ${REPO_URL}"
+      exit 2
+    fi
   fi
   echo "git clone -b ${REPO_BRANCH} ${GIT_ARGS} ${REPO_URL} ${DESTINATION}"
   # Try twice in case of network lossage.
