Fix

diff --git a/git-find-fork b/git-find-fork
--- a/git-find-fork
+++ b/git-find-fork
@@ -19,8 +19,8 @@ echo "which is an obsolete version from https://github.com/plume-lib/plume-scrip
 
 if [ "$#" -ne 3 ]; then
   script=$(basename -- "$0")
-  >&2 echo "Error: $script requires 3 arguments, got $#"
-  >&2 echo "Usage: $script ORG UPSTREAM_ORG REPONAME"
+  echo >&2 "Error: $script requires 3 arguments, got $#"
+  echo >&2 "Usage: $script ORG UPSTREAM_ORG REPONAME"
   exit 1
 fi
 
