Clarify error message

diff --git a/git-find-branch b/git-find-branch
--- a/git-find-branch
+++ b/git-find-branch
@@ -10,8 +10,9 @@
 
 if [ "$#" -eq 1 ]; then
     script=$(basename -- "$0")
-    >&2 echo "Error: $script requires 2 arguments, got $#, using \"master\""
+    >&2 echo "Error: $script requires 2 arguments, got $#
     >&2 echo "Usage: $script REPO BRANCH"
+    >&2 echo "Returning \"master\""
     echo "master"
     exit 1
 fi
