Improve debugging

diff --git a/git-find-branch b/git-find-branch
--- a/git-find-branch
+++ b/git-find-branch
@@ -8,9 +8,11 @@
 # For example usage within a Travis build, see
 # https://github.com/plume-lib/plume-scripts#usage-of-git-find-forkbranch
 
-if [ "$#" -ne 2 ]; then
-    echo "Error: $0 requires 2 arguments, got $#"
-    echo "Usage: $0 REPO BRANCH"
+if [ "$#" -eq 1 ]; then
+    script=$(basename -- "$0")
+    >&2 echo "Error: $script requires 2 arguments, got $#, using \"master\""
+    >&2 echo "Usage: $script REPO BRANCH"
+    echo "master"
     exit 1
 fi
 
diff --git a/git-find-fork b/git-find-fork
--- a/git-find-fork
+++ b/git-find-fork
@@ -11,8 +11,9 @@
 # https://github.com/plume-lib/plume-scripts#usage-of-git-find-forkbranch
 
 if [ "$#" -ne 3 ]; then
-    echo "Error: $0 requires 3 arguments, got $#"
-    echo "Usage: $0 ORG UPSTREAM_ORG REPONAME"
+    script=$(basename -- "$0")
+    >&2 echo "Error: $script requires 3 arguments, got $#"
+    >&2 echo "Usage: $script ORG UPSTREAM_ORG REPONAME"
     exit 1
 fi
 
